apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    role: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: go-app
  template:
    metadata:
      labels:
        role: go-app
    spec:
      containers:
      - name: go-app
        image: bee7ch/go-test:latest
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 10m