apiVersion: v1
kind: Service
metadata:
  name: go-app-svc
spec:
  selector:
    role: go-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32000
  type: NodePort